### ISSUE TITLE
Tried to run the example, got error

### ISSUE THREAD

**Issue by Bushwazi** [marcusellis05/grunt-tasks#1]
Hello, I tried to run `$ npm install` from the example directory and got the following error.
npm ERR! cb() never called!

**Comment by marcusellis05** [comment]
Yeah sorry about that. I'm noticing a bad entry in the list of dependencies. I'm out of the country for a few weeks without my laptop. But would happily accept a PR that fixes it.

**Comment by marcusellis05** [comment]
Fixed the issue with the example in v0.1.4.
